# https://hub.docker.com/_/mysql
# TODO: is basic authentification enough for our purposes? 
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${password:?password needs to be set in the .env file}
    ports:
      - 3306:3306
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
      - ${mysql_datadir:-./datadir}:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
